# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"W\n\x07Request\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\r\n\x05login\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\"\'\n\x08Response\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04info\x18\x02 \x01(\t\"9\n\nIOTRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=14
  _globals['_REQUEST']._serialized_end=101
  _globals['_RESPONSE']._serialized_start=103
  _globals['_RESPONSE']._serialized_end=142
  _globals['_IOTREQUEST']._serialized_start=144
  _globals['_IOTREQUEST']._serialized_end=201
# @@protoc_insertion_point(module_scope)
